/*
 * ============================================================
 * CATÁLOGO DE ATIVIDADES — decisão de roteiro, dez/2026
 * ============================================================
 * Cada entrada carrega o que é preciso para DECIDIR:
 *   tickets  — onde comprar, quando abre a venda, se esgota
 *   bestTime — melhor horário/dia para ir
 *   december — o que muda especificamente em dezembro
 *   says     — o que as pessoas relatam (elogios e reclamações)
 *   swapFor  — o que sai do roteiro-base se isto entrar
 *
 * Pesquisa de dezembro/2026 conferida em set/2026. Horários de
 * pôr do sol: Tóquio ~16h30, Kyoto/Osaka ~16h50 — dia curto,
 * mirante e templo precisam ser de dia.
 */

export const ACT_CATEGORIES = [
  { id: "vista", label: "Vistas e mirantes", emoji: "🌆", color: "#6366f1" },
  { id: "templo", label: "Templos e jardins", emoji: "⛩️", color: "#f43f5e" },
  { id: "comida", label: "Comida e mercados", emoji: "🍜", color: "#f59e0b" },
  { id: "compras", label: "Compras", emoji: "🛍️", color: "#a855f7" },
  { id: "arte", label: "Arte e museus", emoji: "🎨", color: "#0ea5e9" },
  { id: "parque", label: "Parques temáticos", emoji: "🎢", color: "#22c55e" },
  { id: "noite", label: "Vida noturna", emoji: "🍸", color: "#ec4899" },
  { id: "natureza", label: "Natureza e caminhada", emoji: "🌿", color: "#14b8a6" },
  { id: "natal", label: "Natal e iluminações", emoji: "🎄", color: "#ef4444" },
  { id: "batevolta", label: "Bate-volta", emoji: "🚄", color: "#eab308" },
];

export const EFFORT = {
  baixo: { label: "Encaixa fácil", color: "#22c55e" },
  medio: { label: "Ocupa um bloco", color: "#f59e0b" },
  alto: { label: "Come o dia", color: "#ef4444" },
};

/*
 * city: toquio | kyoto | osaka
 * match: pedro | gio | ambos
 * hours: duração realista em horas (usada pelo otimizador)
 * costBRL: entrada por pessoa (0 = grátis)
 */
export const ACTIVITIES = [
  // ==================== TÓQUIO ====================
  {
    id: "t-shibuya-sky", city: "toquio", area: "Shibuya", cat: "vista",
    name: "Shibuya Sky", hours: 1.5, costBRL: 147, costYen: 2500,
    match: "ambos", level: "alto", effort: "baixo", rating: 4.6,
    lat: 35.6580, lng: 139.7016,
    what: "Rooftop aberto no 47º andar, sem vidro e sem teto. Você vê o cruzamento de Shibuya de cima e, em dia limpo, o Fuji no horizonte.",
    says: {
      good: ["Único rooftop realmente aberto de Tóquio", "A rede de sofás no chão (Sky Edge) rende as melhores fotos", "#3 entre 364 atrações de Shibuya"],
      bad: ["Fila para a beirada nos horários de pôr do sol", "Fecha a área externa se houver vento forte ou chuva — e aí não tem reembolso", "Proibido tripé e bastão de selfie"],
    },
    tickets: {
      where: "Site oficial (shibuya-sky.com) ou KKday/Klook",
      when: "Abre 2 semanas antes, à meia-noite do horário do Japão (12h do dia anterior no Brasil)",
      sellsOut: "Sim — os slots de pôr do sol esgotam em segundos",
      tip: "Se o pôr do sol esgotar, pegue o slot 1h-1h30 ANTES: você entra de dia e fica até escurecer. KKday costuma ter um lote separado para estrangeiro.",
    },
    bestTime: "Em dezembro o sol se põe ~16h30 em Tóquio. Slot ideal: entrada 15h30–16h.",
    december: "Dia curto trabalha a favor: dá para ver o pôr do sol e ainda emendar jantar. Ar seco de inverno = maior chance de ver o Fuji do que no verão. Leve casaco pesado — lá em cima venta muito.",
    swapFor: "Encaixa no fim da tarde do dia de Shibuya, sem tirar nada.",
    combines: ["t-shibuya-crossing", "t-nonbei"],
  },
  {
    id: "t-disneysea", city: "toquio", area: "Urayasu", cat: "parque",
    name: "Tokyo DisneySea", hours: 11, costBRL: 355, costYen: 10900,
    match: "pedro", level: "alto", effort: "alto", rating: 4.8,
    lat: 35.6267, lng: 139.8851,
    what: "O parque Disney mais bonito do mundo, e só existe em Tóquio. Em dezembro roda a temporada de Natal com decoração e show próprios.",
    says: {
      good: ["Consenso de que é o parque mais bem ambientado do planeta", "Fantasy Springs (área nova de Frozen/Rapunzel/Peter Pan) puxa fila enorme", "Comida de parque muito acima da média — gyoza dog, churros salgados"],
      bad: ["Sem Premier Access (pago à parte, por atração) as filas passam de 2h", "App só funciona bem com chip japonês/eSIM ativo", "Dezembro é frio e boa parte da fila é ao ar livre"],
    },
    tickets: {
      where: "Site oficial (tokyodisneyresort.jp) — versão em inglês funciona com cartão internacional",
      when: "Venda abre com ~2 meses de antecedência, para data E parque específicos",
      sellsOut: "Sim, fins de semana de dezembro esgotam",
      tip: "Compre o Premier Access das 2-3 atrações que mais quer JÁ NO DIA, pelo app, assim que entrar no parque. Preço varia por atração (¥1.500–2.500).",
    },
    bestTime: "Chegar 8h (o portão abre 9h, mas a fila começa antes). Sair depois do show noturno, ~20h30–21h.",
    december: "A temporada de Natal roda até 25/12 — vocês pegam em cheio. Multidão sobe ao longo do mês, mas o caos mesmo é 27/12–03/01, que vocês evitam. Sexta 11/12 é a melhor escolha da semana de vocês.",
    swapFor: "Come um dia inteiro de Tóquio. Na versão com DisneySea, Ginza ou o segundo bloco de compras sai.",
    combines: [],
  },
  {
    id: "t-teamlab-tokyo", city: "toquio", area: "Toyosu / Azabudai", cat: "arte",
    name: "teamLab Planets ou Borderless (Tóquio)", hours: 3, costBRL: 124, costYen: 3800,
    match: "gio", level: "medio", effort: "medio", rating: 4.5,
    lat: 35.6491, lng: 139.7897,
    what: "Arte digital imersiva. No Planets você anda na água até o joelho; no Borderless as salas mudam sozinhas enquanto você circula.",
    says: {
      good: ["A sala de água com as carpas projetadas é o ponto alto", "Rende foto como nenhum outro lugar de Tóquio"],
      bad: ["Redundante se já forem ao de Kyoto", "Planets: você fica descalço e com a calça enrolada — leve short ou calça que dobra", "Chão espelhado: quem for de saia recebe um short emprestado"],
    },
    tickets: {
      where: "teamlab.art (oficial), Klook ou KKday",
      when: "Abre com meses de antecedência, por horário",
      sellsOut: "Sim, principalmente fim de semana",
      tip: "Se já decidiram pelo de Kyoto, pule este — é a mesma linguagem visual.",
    },
    bestTime: "Primeiro horário da manhã (10h) é o menos cheio.",
    december: "Sem diferença sazonal relevante — é tudo indoor e climatizado. Bom plano de dia chuvoso.",
    swapFor: "Só entra se sobrar tempo na versão sem DisneySea.",
    combines: ["t-odaiba"],
  },
  {
    id: "t-shibuya-crossing", city: "toquio", area: "Shibuya", cat: "vista",
    name: "Cruzamento de Shibuya + Hachiko", hours: 1, costBRL: 0,
    match: "ambos", level: "alto", effort: "baixo", rating: 4.4,
    lat: 35.6595, lng: 139.7005,
    what: "O cruzamento mais famoso do mundo, com até 3.000 pessoas por sinal verde. A estátua do cachorro Hachiko fica ao lado.",
    says: {
      good: ["Atravessar é de graça e vira memória", "Vista de cima grátis: Starbucks do Tsutaya ou passarela do Magnet"],
      bad: ["A fila do Starbucks para a janela é longa", "Hachiko é bem menor do que as fotos sugerem"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "A passarela do Mag's Park (Magnet by Shibuya109, ¥600) é o melhor ângulo pago." },
    bestTime: "Fim de tarde, quando os letreiros acendem e ainda há movimento de gente saindo do trabalho.",
    december: "Escurece 16h30, então a cena com neon acontece mais cedo — dá para ver de dia e de noite no mesmo passeio.",
    swapFor: "Já está no roteiro-base.",
    inBase: true,
    combines: ["t-shibuya-sky", "t-nonbei"],
  },
  {
    id: "t-tsukiji", city: "toquio", area: "Tsukiji", cat: "comida",
    name: "Tsukiji Outer Market", hours: 2.5, costBRL: 0, spendBRL: 120,
    match: "ambos", level: "alto", effort: "medio", rating: 4.5,
    lat: 35.6654, lng: 139.7707,
    what: "O mercado externo que ficou depois que o atacado mudou para Toyosu. Sushi de café da manhã, tamagoyaki no espeto, ostras grelhadas na hora.",
    says: {
      good: ["Comida de rua é a prioridade nº1 combinada de vocês — este é o melhor lugar de Tóquio para isso", "Sushi de balcão de ¥2.500 melhor que restaurante caro no Brasil"],
      bad: ["Lotado depois das 10h", "Muitas barracas fecham 14h", "Algumas só aceitam dinheiro"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Leve ¥5.000 em espécie por pessoa — várias barracas não passam cartão." },
    bestTime: "8h–9h30. Vá com fome de verdade.",
    december: "Alta temporada de ostra e caranguejo — as barracas de grelhado ficam melhores em dezembro que no verão. Frio ajuda: chá quente entre uma barraca e outra.",
    swapFor: "Já está no roteiro-base (sábado 12/12 de manhã).",
    inBase: true,
    combines: ["t-ginza"],
  },
  {
    id: "t-sensoji", city: "toquio", area: "Asakusa", cat: "templo",
    name: "Senso-ji + rua Nakamise", hours: 2, costBRL: 0, spendBRL: 60,
    match: "ambos", level: "alto", effort: "baixo", rating: 4.5,
    lat: 35.7148, lng: 139.7967,
    what: "Templo mais antigo de Tóquio (ano 645), com o portão Kaminarimon e uma rua de 250m de barracas até a entrada.",
    says: {
      good: ["O portão com a lanterna gigante é a foto clássica de Tóquio", "Nakamise tem senbei e ningyo-yaki feitos na hora"],
      bad: ["Cheio de turista o dia inteiro a partir das 9h", "As barracas são caras para o que vendem"],
    },
    tickets: { where: "Não precisa — templo é grátis", when: "—", sellsOut: "Não", tip: "Omikuji (papel da sorte) ¥100. Se der azar, amarra no varal e deixa lá." },
    bestTime: "Antes das 8h30 o lugar é praticamente vazio e a luz é melhor.",
    december: "Em 17–19/12 rola a Hagoita-Ichi, feira de raquetes decoradas de Ano Novo, no pátio do templo — mas vocês já estarão no Kansai. Dezembro tem ar limpo e o templo iluminado à noite fica bonito.",
    swapFor: "Já está no roteiro-base (quinta 10/12).",
    inBase: true,
    combines: ["t-kappabashi", "t-skytree"],
  },
  {
    id: "t-skytree", city: "toquio", area: "Oshiage", cat: "vista",
    name: "Tokyo Skytree", hours: 2, costBRL: 117, costYen: 3100,
    match: "ambos", level: "medio", effort: "medio", rating: 4.3,
    lat: 35.7101, lng: 139.8107,
    what: "Torre mais alta do Japão (634m). Dois deques: 350m e 450m (este custa mais).",
    says: {
      good: ["Vista mais alta do país", "O shopping da base (Solamachi) resolve chuva e compras"],
      bad: ["Tudo atrás de vidro — quem já foi no Shibuya Sky costuma achar inferior", "Caro para o que entrega", "Se o tempo fechar, você paga e não vê nada"],
    },
    tickets: {
      where: "tokyo-skytree.jp (oficial) — estrangeiro tem fila rápida com passaporte",
      when: "Dá para comprar no dia, mas o horário marcado evita fila na base",
      sellsOut: "Raramente",
      tip: "Só suba se o dia estiver limpo. Se estiver nublado, troque pelo observatório GRÁTIS do Governo Metropolitano em Shinjuku.",
    },
    bestTime: "Entre 15h e 16h para pegar dia e noite na mesma subida.",
    december: "Melhor mês do ano para visibilidade — ar seco. Em dia muito limpo dá para ver o Fuji. A torre tem iluminação especial de Natal.",
    swapFor: "Já está no roteiro-base (quinta 10/12).",
    inBase: true,
    combines: ["t-sensoji"],
  },
  {
    id: "t-tocho", city: "toquio", area: "Shinjuku", cat: "vista",
    name: "Observatório GRÁTIS do Governo Metropolitano", hours: 1, costBRL: 0,
    match: "ambos", level: "medio", effort: "baixo", rating: 4.3,
    lat: 35.6896, lng: 139.6921,
    what: "45º andar do prédio do governo de Tóquio. Vista de 360° sem pagar nada.",
    says: {
      good: ["Melhor custo-benefício da cidade: R$0", "Em dia limpo vê o Fuji", "À noite tem projeção mapeada na fachada do prédio"],
      bad: ["Vidro com reflexo atrapalha foto", "Fila pode dar 20-30min no fim de semana"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Torre Sul costuma ter menos fila que a Norte." },
    bestTime: "Fim de tarde. Fecha 22h (Torre Sul), então dá para ir depois do jantar.",
    december: "A projeção na fachada tem versão de Natal. Como escurece 16h30, dá para ver dia e noite numa visita só.",
    swapFor: "Substituto grátis do Skytree em dia nublado.",
    combines: ["t-omoide", "t-golden-gai"],
  },
  {
    id: "t-omoide", city: "toquio", area: "Shinjuku", cat: "comida",
    name: "Omoide Yokocho (Piss Alley)", hours: 2, costBRL: 0, spendBRL: 110,
    match: "ambos", level: "alto", effort: "baixo", rating: 4.4,
    lat: 35.6930, lng: 139.6994,
    what: "Vielas de yakitori dos anos 40, fumaça, lanternas e balcões de 6 lugares.",
    says: {
      good: ["A Tóquio de filme", "Espetos ¥150–300, cerveja barata"],
      bad: ["Alguns bares cobram otoshi (couvert) ¥300–500 sem avisar", "Muito apertado e cheira a fumaça — a roupa fica com cheiro"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Olhe o preço na porta antes de sentar. Lugares com menu em inglês cobram mais." },
    bestTime: "A partir das 18h, quando os balcões acendem.",
    december: "Frio é aliado: os balcões esquentam com o grelhado e a fumaça, e é aí que o lugar fica mais gostoso.",
    swapFor: "Já está no roteiro-base (sexta 11/12 à noite).",
    inBase: true,
    combines: ["t-golden-gai", "t-tocho"],
  },
  {
    id: "t-golden-gai", city: "toquio", area: "Shinjuku", cat: "noite",
    name: "Golden Gai", hours: 2, costBRL: 0, spendBRL: 180,
    match: "ambos", level: "medio", effort: "baixo", rating: 4.2,
    lat: 35.6938, lng: 139.7048,
    what: "200 bares minúsculos (4 a 8 lugares cada) em seis vielas que sobraram da Tóquio dos anos 50.",
    says: {
      good: ["Cada bar tem uma temática — punk, jazz, cinema", "Conversa com estranho acontece naturalmente"],
      bad: ["Couvert de ¥500–1.500 é a regra", "Alguns bares recusam estrangeiro abertamente", "Cabe pouca gente: em dupla já ocupa 1/3 do bar"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Entre nos que têm preço e 'welcome' escritos na porta. Se não tiver placa, provavelmente é só para frequentador." },
    bestTime: "Depois das 21h — antes disso muitos ainda estão fechados.",
    december: "Sem mudança sazonal. Lembre do último trem: depois de 0h30 o táxi de volta sai ¥3.000–6.000.",
    swapFor: "Combina com a noite de Shinjuku que já está no roteiro.",
    combines: ["t-omoide"],
  },
  {
    id: "t-nonbei", city: "toquio", area: "Shibuya", cat: "noite",
    name: "Nonbei Yokocho", hours: 2, costBRL: 0, spendBRL: 120,
    match: "ambos", level: "alto", effort: "baixo", rating: 4.3,
    lat: 35.6600, lng: 139.7020,
    what: "Duas vielas de bares minúsculos embaixo do trilho do trem, a 2 minutos do cruzamento de Shibuya.",
    says: {
      good: ["O 'Golden Gai secreto' — mesma vibe, menos turista", "O trem passando em cima faz parte da experiência"],
      bad: ["Bares de 4 lugares: às vezes você espera na rua", "Também tem couvert em alguns"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Como fica colado no Shibuya Sky, é o fecho natural daquele dia." },
    bestTime: "20h em diante.",
    december: "Vielas cobertas e aquecidas por dentro — bom refúgio do frio.",
    swapFor: "Encaixa na noite de Shibuya sem tirar nada.",
    combines: ["t-shibuya-sky", "t-shibuya-crossing"],
  },
  {
    id: "t-akihabara", city: "toquio", area: "Akihabara", cat: "compras",
    name: "Akihabara — eletrônicos, games e anime", hours: 3, costBRL: 0, spendBRL: 250,
    match: "ambos", level: "alto", effort: "medio", rating: 4.4,
    lat: 35.7022, lng: 139.7741,
    what: "Bairro de eletrônicos que virou meca geek. Yodobashi (9 andares), Super Potato (games retrô), gachapon aos milhares.",
    says: {
      good: ["Yodobashi Akiba é o melhor lugar do país para tech", "Tax-free acima de ¥5.000 com passaporte + cupom de 5-7% no app da loja", "Super Potato tem cartucho testado e garantido"],
      bad: ["Promotor de maid café aborda o tempo todo na rua", "Preço de colecionável é melhor em Nakano Broadway"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Baixe o app da Yodobashi antes: gera cupom de desconto que soma com o tax-free." },
    bestTime: "Tarde. Lojas abrem 10h–11h e vão até 20h–21h.",
    december: "Bônus de dezembro: as lojas soltam fukubukuro (sacolas-surpresa de Ano Novo) a partir do fim do mês — vocês saem antes, mas já tem promoção de Natal rolando.",
    swapFor: "Já está no roteiro-base (quinta 10/12 à noite).",
    inBase: true,
    combines: ["t-nakano"],
  },
  {
    id: "t-nakano", city: "toquio", area: "Nakano", cat: "compras",
    name: "Nakano Broadway", hours: 2, costBRL: 0, spendBRL: 180,
    match: "ambos", level: "medio", effort: "medio", rating: 4.4,
    lat: 35.7089, lng: 139.6657,
    what: "Shopping retrô com 30+ lojas Mandarake: figures raras, cels originais de anime, mangá vintage.",
    says: {
      good: ["Preço melhor que Akihabara para colecionável", "Menos turista, mais colecionador de verdade"],
      bad: ["Prédio é feio e confuso", "Quem não coleciona acha sem graça"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Se forem comprar figure/mangá, venham aqui ANTES de Akihabara para comparar preço." },
    bestTime: "Tarde — a maioria das lojas abre só ao meio-dia.",
    december: "Sem diferença sazonal. Tudo coberto, bom para dia frio.",
    swapFor: "Troca direta com o segundo bloco de compras (Ueno/Ameyoko) se quiserem algo mais nichado.",
    combines: ["t-akihabara"],
  },
  {
    id: "t-harajuku", city: "toquio", area: "Harajuku", cat: "compras",
    name: "Harajuku: Takeshita + Cat Street", hours: 3, costBRL: 0, spendBRL: 200,
    match: "ambos", level: "alto", effort: "medio", rating: 4.3,
    lat: 35.6702, lng: 139.7026,
    what: "Takeshita é a rua da moda jovem e dos crepes; Cat Street é a paralela que os locais preferem, com streetwear e brechó.",
    says: {
      good: ["Cat Street liga Harajuku a Shibuya a pé — dá para fazer os dois bairros sem pegar trem", "Crepe da Marion (¥700) é o clássico desde 1976"],
      bad: ["Takeshita fica intransitável no fim de semana", "Muita loja igual"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Faça Takeshita rápido e gaste o tempo na Cat Street e na Omotesando." },
    bestTime: "Manhã em dia de semana. Fim de semana é caos.",
    december: "A Omotesando ganha iluminação de Natal nos olmos da avenida — uma das mais bonitas de Tóquio, e roda até o Natal.",
    swapFor: "Já está no roteiro-base (sexta 11/12).",
    inBase: true,
    combines: ["t-meiji", "t-omotesando-illum"],
  },
  {
    id: "t-meiji", city: "toquio", area: "Harajuku", cat: "templo",
    name: "Santuário Meiji Jingu", hours: 1.5, costBRL: 0,
    match: "gio", level: "alto", effort: "baixo", rating: 4.5,
    lat: 35.6764, lng: 139.6993,
    what: "Santuário xintoísta dentro de uma floresta plantada de 70 hectares, colada em Harajuku.",
    says: {
      good: ["O contraste de sair do caos de Harajuku e entrar numa floresta em 2 minutos", "Grátis", "Casamento xintoísta acontece com frequência e dá para assistir de longe"],
      bad: ["A caminhada da entrada até o santuário dá uns 10-15min", "O prédio em si é sóbrio — quem espera templo dourado se frustra"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "O jardim interno (¥500) só vale na temporada de íris, em junho. Em dezembro, pule." },
    bestTime: "Logo na abertura (nasce do sol, ~6h45 em dezembro) o bosque fica só seu.",
    december: "Fecha ao pôr do sol, ou seja ~16h30 — não dá para deixar para o fim da tarde. Em dezembro a floresta fica com o ar gelado e quase sem gente de manhã.",
    swapFor: "Já está no roteiro-base (sexta 11/12).",
    inBase: true,
    combines: ["t-harajuku"],
  },
  {
    id: "t-omotesando-illum", city: "toquio", area: "Omotesando", cat: "natal",
    name: "Iluminação da Omotesando", hours: 1, costBRL: 0,
    match: "pedro", level: "alto", effort: "baixo", rating: 4.5,
    lat: 35.6656, lng: 139.7126,
    what: "Os olmos da avenida Omotesando acesos por 1,1km — a iluminação mais elegante de Tóquio.",
    says: {
      good: ["Gratuita e no caminho de quem já vai a Harajuku", "Menos aglomerada que Roppongi"],
      bad: ["É 'só' uma rua iluminada — quem espera atração fica decepcionado"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Combine com o jantar depois de Harajuku." },
    bestTime: "A partir das 17h, quando acende.",
    december: "Roda de fim de novembro até o Natal — vocês pegam. Pedro marcou iluminações como desejo; Gio disse que corta fácil. Esta é a de menor custo de tempo.",
    swapFor: "Zero custo de roteiro: acontece no caminho.",
    combines: ["t-harajuku"],
  },
  {
    id: "t-midtown-illum", city: "toquio", area: "Roppongi", cat: "natal",
    name: "Iluminações de Roppongi (Midtown + Keyakizaka)", hours: 1.5, costBRL: 0,
    match: "pedro", level: "alto", effort: "baixo", rating: 4.6,
    lat: 35.6656, lng: 139.7310,
    what: "A avenida Keyakizaka acende com a Tokyo Tower emoldurada no fim da rua. O Midtown faz um campo de luzes azuis.",
    says: {
      good: ["A foto da Keyakizaka com a Tokyo Tower ao fundo é A foto de dezembro em Tóquio", "Mori Art Museum fica ali e abre até 22h"],
      bad: ["Muito cheio nos fins de semana de dezembro", "O trecho bom da Keyakizaka é curto"],
    },
    tickets: { where: "Gratuito", when: "—", sellsOut: "Não", tip: "Vá em dia de semana. O ângulo clássico é da passarela no meio da Keyakizaka." },
    bestTime: "17h–18h30 em dia útil.",
    december: "É o auge exatamente nas datas de vocês. Já está no roteiro-base como 'Roppongi Hills / Tokyo Tower, vista noturna' do sábado 12/12.",
    swapFor: "Já contemplado no roteiro-base de sábado.",
    inBase: true,
    combines: ["t-tokyo-tower", "t-mori"],
  },
  {
    id: "t-tokyo-tower", city: "toquio", area: "Minato", cat: "vista",
    name: "Tokyo Tower", hours: 1.5, costBRL: 49, costYen: 1500,
    match: "ambos", level: "alto", effort: "baixo", rating: 4.3,
    lat: 35.6586, lng: 139.7454,
    what: "A torre vermelha de 1958. Mais baixa e mais barata que a Skytree, e muito mais fotogênica por fora.",
    says: {
      good: ["Mais charmosa que a Skytree", "O deck de 150m tem piso de vidro"],
      bad: ["Vista inferior à da Skytree", "Muita gente acha que vale mais ver de fora do que subir"],
    },
    tickets: { where: "Bilheteria ou site oficial", when: "Dá para comprar no dia", sellsOut: "Não", tip: "A melhor foto da torre é de graça, do templo Zojo-ji, logo abaixo." },
    bestTime: "Fim de tarde, para pegar a torre acesa.",
    december: "Em dezembro a torre usa iluminação especial de inverno. Como escurece 16h30, dá para ver acesa já no fim da tarde.",
    swapFor: "Já contemplado no bloco de sábado do roteiro-base.",
    inBase: true,
    combines: ["t-midtown-illum"],
  },
  {
    id: "t-mori", city: "toquio", area: "Roppongi", cat: "arte",
    name: "Mori Art Museum + Tokyo City View", hours: 2, costBRL: 72, costYen: 2200,
    match: "gio", level: "medio", effort: "medio", rating: 4.4,
    lat: 35.6605, lng: 139.7292,
    what: "Museu de arte contemporânea no 53º andar, com mirante junto. Aberto até 22h — o único museu noturno relevante da cidade.",
    says: {
      good: ["Arte + vista noturna no mesmo ingresso", "Aberto até tarde, encaixa depois do jantar"],
      bad: ["A exposição muda: pode calhar de não ser do gosto de vocês", "Vista é atrás de vidro"],
    },
    tickets: { where: "mori.art.museum ou bilheteria", when: "No dia", sellsOut: "Não", tip: "Confira a exposição em cartaz antes de decidir — a qualidade varia muito." },
    bestTime: "Entrar ~19h: você vê a arte e sai com a cidade acesa.",
    december: "Museus são o ponto em que vocês mais divergem (Gio 4, Pedro 7). Este é o mais 'palatável' para os dois, porque metade do ingresso é vista.",
    swapFor: "Substitui bem o Skytree em dia de chuva, ou emenda com a iluminação de Roppongi.",
    combines: ["t-midtown-illum"],
  },
  {
    id: "t-ginza", city: "toquio", area: "Ginza", cat: "compras",
    name: "Ginza + depachika", hours: 2.5, costBRL: 0, spendBRL: 200,
    match: "ambos", level: "medio", effort: "medio", rating: 4.2,
    lat: 35.6717, lng: 139.7650,
    what: "A avenida de luxo de Tóquio: Uniqlo de 12 andares, Itoya (papelaria de 12 andares), MUJI flagship com padaria.",
    says: {
      good: ["Depachika (andar de comida do subsolo) do Mitsukoshi é um espetáculo", "Após 19h30 os bentos gourmet caem pela metade do preço"],
      bad: ["Cara e formal", "Morre cedo — não é bairro de noite"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Sábado e domingo à tarde a avenida principal fecha para carros e vira calçadão." },
    bestTime: "Fim de tarde, e o depachika depois das 19h30 pelo desconto.",
    december: "As vitrines de Natal de Ginza são um passeio à parte. Na versão COM DisneySea, este é o bloco mais provável de sair do roteiro.",
    swapFor: "É o candidato natural a ser cortado se o DisneySea entrar.",
    inBase: true,
    combines: ["t-tsukiji"],
  },
  {
    id: "t-ueno", city: "toquio", area: "Ueno", cat: "comida",
    name: "Ueno + Ameyoko", hours: 3, costBRL: 0, spendBRL: 150,
    match: "ambos", level: "alto", effort: "medio", rating: 4.2,
    lat: 35.7107, lng: 139.7743,
    what: "Mercado de rua barulhento que nasceu no pós-guerra, embaixo da linha do trem. Comida, tênis, cosmético, tudo em promoção gritada.",
    says: {
      good: ["Preço melhor que qualquer shopping", "Barracas de espetinho e fruta para comer andando"],
      bad: ["Bagunçado e apertado", "Qualidade do que se vende varia muito"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Em dezembro os vendedores fazem leilão de caranguejo e atum para o Ano Novo — vale só pelo show." },
    bestTime: "Tarde, quando os vendedores ficam mais animados.",
    december: "A última semana de dezembro é o auge do Ameyoko (compras de Ano Novo). Vocês pegam o começo do movimento.",
    swapFor: "Já está no roteiro-base (domingo 13/12).",
    inBase: true,
    combines: ["t-yanaka"],
  },
  {
    id: "t-yanaka", city: "toquio", area: "Yanaka", cat: "natureza",
    name: "Yanaka Ginza (Tóquio antiga)", hours: 2.5, costBRL: 0, spendBRL: 60,
    match: "ambos", level: "medio", effort: "medio", rating: 4.4,
    lat: 35.7276, lng: 139.7668,
    what: "Bairro que escapou dos bombardeios e do terremoto: rua comercial de madeira, gatos, templos pequenos e um cemitério arborizado.",
    says: {
      good: ["A Tóquio que sobrou do século passado", "Croquete de menchi-katsu na rua, ¥250", "Quase sem turista"],
      bad: ["Não tem 'atração' — é passear", "Rua principal é curta, 20 minutos e acabou"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Emende com o santuário Nezu, que tem um túnel de toriis vermelhos em miniatura — o 'Fushimi de Tóquio'." },
    bestTime: "Manhã, com o comércio abrindo.",
    december: "Manhã gelada e vazia é exatamente a atmosfera do bairro. Combina com o ritmo de 'acordar 6h30' que vocês dois toparam.",
    swapFor: "Troca por meia manhã do bloco de Ueno (ficam a 10 min a pé um do outro).",
    combines: ["t-ueno"],
  },
  {
    id: "t-shimokita", city: "toquio", area: "Shimokitazawa", cat: "compras",
    name: "Shimokitazawa (brechós)", hours: 3, costBRL: 0, spendBRL: 200,
    match: "ambos", level: "alto", effort: "medio", rating: 4.5,
    lat: 35.6614, lng: 139.6682,
    what: "Bairro indie com a maior concentração de brechó de Tóquio, cafés e lojas de vinil.",
    says: {
      good: ["O melhor vintage da cidade — melhor que Harajuku em preço", "Flamingo, Chicago e New York Joe são os nomes citados", "Bairro pequeno, dá para andar tudo a pé"],
      bad: ["Lojas abrem só ao meio-dia", "Se não gostar de roupa usada, não tem muito mais"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Compras é a prioridade nº2 combinada de vocês — se for para dedicar um bloco a garimpo, é aqui." },
    bestTime: "A partir das 12h. Reserve 3h.",
    december: "Casaco de inverno de segunda mão sai muito barato — e vocês vão precisar de camada extra de qualquer jeito.",
    swapFor: "Troca direta com o bloco de compras de domingo 13/12.",
    combines: ["t-nakameguro"],
  },
  {
    id: "t-nakameguro", city: "toquio", area: "Nakameguro", cat: "compras",
    name: "Nakameguro + Daikanyama", hours: 2.5, costBRL: 0, spendBRL: 150,
    match: "gio", level: "medio", effort: "medio", rating: 4.4,
    lat: 35.6440, lng: 139.6982,
    what: "Canal arborizado com lojinhas de design, o Starbucks Reserve Roastery de 4 andares e a livraria Tsutaya em Daikanyama.",
    says: {
      good: ["A Tóquio elegante e tranquila", "O Roastery vale a visita mesmo sem tomar café"],
      bad: ["Caro", "Sem as cerejeiras (abril) o canal é 'só' um canal"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "A Tsutaya de Daikanyama abre até tarde e tem um bar dentro." },
    bestTime: "Fim de tarde, com as luzes do canal acesas.",
    december: "O canal recebe iluminação de inverno com luzes azuis refletindo na água. Fica bonito e é bem menos cheio que Roppongi.",
    swapFor: "Combina com Shimokitazawa no mesmo dia (mesma linha de trem).",
    combines: ["t-shimokita"],
  },
  {
    id: "t-kappabashi", city: "toquio", area: "Asakusa", cat: "compras",
    name: "Kappabashi (rua das facas)", hours: 1.5, costBRL: 0, spendBRL: 250,
    match: "ambos", level: "medio", effort: "baixo", rating: 4.3,
    lat: 35.7139, lng: 139.7887,
    what: "Rua dos utensílios de cozinha profissional: facas japonesas, cerâmica, e a famosa comida de plástico de vitrine.",
    says: {
      good: ["Faca japonesa boa sai ¥8.000–15.000 e várias lojas gravam seu nome de graça", "Souvenir que dura a vida toda"],
      bad: ["Fecha cedo (17h) e quase tudo fecha domingo", "Facas na bagagem de mão não passam — tem que despachar"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Fica a 10 min a pé de Asakusa: encaixa no mesmo bloco do Senso-ji sem custo extra de deslocamento." },
    bestTime: "Manhã ou início da tarde, em dia de semana.",
    december: "Sem sazonalidade. Atenção: se comprarem faca, ela precisa ir na mala despachada na volta.",
    swapFor: "Encaixa no dia de Asakusa sem tirar nada.",
    combines: ["t-sensoji"],
  },
  {
    id: "t-odaiba", city: "toquio", area: "Odaiba", cat: "vista",
    name: "Odaiba + Gundam gigante", hours: 3.5, costBRL: 0, spendBRL: 120,
    match: "ambos", level: "baixo", effort: "medio", rating: 4.0,
    lat: 35.6252, lng: 139.7756,
    what: "Ilha artificial com o Gundam de 20m que se mexe, shoppings e vista da Rainbow Bridge.",
    says: {
      good: ["O Gundam 'transforma' em horários fixos (11h/13h/15h/17h)", "A vista da ponte iluminada com a cidade atrás é ótima"],
      bad: ["Tudo é longe de tudo dentro da ilha", "Muitos acham que não justifica meio dia", "O trem (Yurikamome) é caro: ¥330 só de ida"],
    },
    tickets: { where: "Gratuito (o Gundam é externo)", when: "—", sellsOut: "Não", tip: "Se forem, vá no fim da tarde para pegar a transformação das 17h já com a ponte acesa." },
    bestTime: "Chegada 15h30–16h.",
    december: "A ilha tem iluminação de inverno e a Rainbow Bridge acende cedo por causa do dia curto. É opção de 'match baixo' — só entra se sobrar tempo.",
    swapFor: "Meio dia inteiro: só cabe na versão sem DisneySea.",
    combines: ["t-teamlab-tokyo"],
  },
  {
    id: "t-sumo-asageiko", city: "toquio", area: "Ryogoku", cat: "arte",
    name: "Treino matinal de sumô (asageiko)", hours: 2.5, costBRL: 390, costYen: 12000,
    match: "pedro", level: "medio", effort: "medio", rating: 4.6,
    lat: 35.6970, lng: 139.7935,
    what: "Em dezembro NÃO há torneio (o de janeiro começa dia 10). Mas dá para assistir ao treino da manhã dentro de um estábulo (heya), a poucos metros dos lutadores.",
    says: {
      good: ["Muito mais íntimo que o torneio — você fica na mesma sala", "Quem foi descreve como o momento mais 'Japão de verdade' da viagem"],
      bad: ["Caro para 2h", "Regras rígidas: silêncio absoluto, sem flash, sentado no chão (formal)", "Precisa de guia/intermediário — não dá para aparecer sozinho"],
    },
    tickets: {
      where: "Agências de tour (Voyagin, Klook, GetYourGuide) — procure 'sumo morning practice Tokyo'",
      when: "Reservar com 1-2 semanas de antecedência",
      sellsOut: "Sim, as vagas são poucas (grupos de 10-20)",
      tip: "Confirme que o tour é numa heya de verdade e não numa demonstração encenada para turista.",
    },
    bestTime: "Começa 7h–8h da manhã. Exige acordar cedo — o que vocês dois disseram topar.",
    december: "Justamente por não ter torneio, os estábulos estão treinando para janeiro: é o período de treino mais intenso do ano.",
    swapFor: "Ocupa a manhã de um dos dias — encaixa bem no domingo 13/12, antes de Ueno.",
    combines: ["t-ueno"],
  },

  // ==================== KYOTO ====================
  {
    id: "k-teamlab", city: "kyoto", area: "Centro", cat: "arte",
    name: "teamLab Biovortex Kyoto", hours: 2.5, costBRL: 147, costYen: 4500,
    match: "gio", level: "alto", effort: "medio", rating: 4.5,
    lat: 34.9880, lng: 135.7590,
    what: "A unidade de Kyoto do teamLab, aberta em outubro de 2025. Foi a escolhida de vocês (em vez da de Tóquio) para não duplicar.",
    says: {
      good: ["Obras novas, feitas especificamente para este espaço", "Menos lotado que as unidades de Tóquio, por ser mais recente"],
      bad: ["Ingresso com preço variável por data (¥3.800 a ¥5.600) — dia de pico custa quase 50% mais", "Comprar na porta custa ¥200 a mais e só se não tiver esgotado"],
    },
    tickets: {
      where: "teamlab.art (oficial) ou Klook. Oficial aceita VISA, Mastercard, JCB, Amex, Diners e PayPay",
      when: "Venda por horário marcado, aberta com meses de antecedência",
      sellsOut: "Sim — reservar 2 a 3 semanas antes, como já está na sua lista de pendências",
      tip: "Comprando no site oficial você pode MUDAR A DATA do ingresso até 3 vezes pelo próprio QR code. Comprando por revendedor, não pode. Isso é seguro contra imprevisto.",
    },
    bestTime: "Já está marcado para 11h de quarta 16/12 no roteiro-base.",
    december: "Indoor e climatizado — imune a chuva e frio. Dezembro é baixa temporada em Kyoto (depois das folhas de outono), então tende a estar mais tranquilo.",
    swapFor: "Já está no roteiro-base.",
    inBase: true,
    combines: ["k-kinkakuji"],
  },
  {
    id: "k-fushimi", city: "kyoto", area: "Fushimi", cat: "templo",
    name: "Fushimi Inari — subida completa", hours: 3, costBRL: 0,
    match: "pedro", level: "alto", effort: "medio", rating: 4.8,
    lat: 34.9671, lng: 135.7727,
    what: "Milhares de toriis vermelhos subindo a montanha Inari. Grátis e aberto 24h. A subida completa até o topo leva 2–3h.",
    says: {
      good: ["Atração mais bem avaliada do Japão em várias listas", "A partir do meio da subida o turista some e você fica sozinho", "De graça, sempre aberto"],
      bad: ["Os primeiros 15 minutos são um formigueiro de gente até as 16h", "Subida é puxada: escada irregular o tempo todo"],
    },
    tickets: { where: "Não precisa — grátis e sem portão", when: "—", sellsOut: "Não", tip: "É o split já acordado: Pedro sobe inteiro, Gio vê a base e segue para o centro." },
    bestTime: "6h30–7h. Já está assim no roteiro-base, e é a decisão certa.",
    december: "Manhã de dezembro em Kyoto beira 2–5°C: leve camada térmica, mas a subida esquenta rápido. Ar limpo = melhor vista da cidade lá de cima. Como é grátis e 24h, não há risco de fechar.",
    swapFor: "Já está no roteiro-base (terça 15/12).",
    inBase: true,
    combines: ["k-kiyomizu"],
  },
  {
    id: "k-kiyomizu", city: "kyoto", area: "Higashiyama", cat: "templo",
    name: "Kiyomizu-dera + Sannenzaka", hours: 2.5, costBRL: 16, costYen: 500,
    match: "gio", level: "alto", effort: "medio", rating: 4.7,
    lat: 34.9949, lng: 135.7850,
    what: "O templo mais famoso de Kyoto, com palco de madeira suspenso na encosta, construído sem um prego. A descida pelas ladeiras Sannenzaka/Ninenzaka é metade do passeio.",
    says: {
      good: ["Vista da cidade do palco", "As ladeiras de pedra até ele são o trecho mais bonito de Kyoto"],
      bad: ["Fica cheio a partir das 9h", "A subida até lá é ladeira puxada"],
    },
    tickets: { where: "Bilheteria na entrada, ¥500", when: "No dia", sellsOut: "Não", tip: "É o templo nº1 dos dois que vocês combinaram — vale gastar tempo aqui em vez de espalhar por vários." },
    bestTime: "Abre 6h. Indo às 7h você tem as ladeiras quase vazias.",
    december: "Fecha 18h (horário de inverno). O light-up noturno de outono acaba no fim de novembro — nas datas de vocês (14–17/12) provavelmente já terá encerrado. Confirme no site antes de contar com visita noturna.",
    swapFor: "Já está no roteiro-base (terça 15/12 à tarde).",
    inBase: true,
    combines: ["k-fushimi", "k-gion"],
  },
  {
    id: "k-kinkakuji", city: "kyoto", area: "Norte", cat: "templo",
    name: "Kinkaku-ji (Pavilhão Dourado)", hours: 1, costBRL: 16, costYen: 500,
    match: "gio", level: "alto", effort: "baixo", rating: 4.6,
    lat: 35.0394, lng: 135.7292,
    what: "Pavilhão coberto de folha de ouro refletido num lago. O percurso é de mão única e rápido: 45min a 1h.",
    says: {
      good: ["Mais impressionante ao vivo do que nas fotos", "Visita curta — não custa meio dia"],
      bad: ["Percurso é uma fila andando — não dá para demorar", "Não se entra no pavilhão, só se vê de fora"],
    },
    tickets: { where: "Bilheteria, ¥500", when: "No dia", sellsOut: "Não", tip: "Se nevar, corra para cá: Kinkaku-ji com neve é uma das imagens mais raras do Japão." },
    bestTime: "Abre 9h. Chegue na abertura — é quando o lago está mais espelhado.",
    december: "Fecha 17h. Dezembro tem chance real de neve leve em Kyoto, e é quando o templo fica lendário. Fora isso, é baixa temporada: menos fila que em outubro/novembro.",
    swapFor: "Já está no roteiro-base (quarta 16/12).",
    inBase: true,
    combines: ["k-teamlab"],
  },
  {
    id: "k-uji", city: "kyoto", area: "Uji", cat: "comida",
    name: "Uji — capital do matcha + Byodo-in", hours: 5, costBRL: 20, costYen: 600, spendBRL: 180,
    match: "pedro", level: "alto", effort: "medio", rating: 4.5, priority: true,
    lat: 34.8914, lng: 135.8073,
    what: "Cidade a 30min de Kyoto, berço do melhor chá verde do Japão. Tem o templo Byodo-in (o da moeda de ¥10) e uma rua inteira de casas de chá centenárias.",
    says: {
      good: ["Nakamura Tokichi: sobremesa de matcha que as pessoas citam como a melhor da viagem", "O Byodo-in refletido na água é uma das imagens clássicas do país", "Muito menos turista que o centro de Kyoto"],
      bad: ["A fila do Nakamura Tokichi passa de 1h no almoço", "Se não gostar de matcha, a cidade perde metade da graça"],
    },
    tickets: {
      where: "Byodo-in: bilheteria ¥600 (jardim) + ¥300 para entrar no salão da Fênix. Cerimônia formal de chá: reservar no Taihoan (¥1.000)",
      when: "Cidade é livre; cerimônia formal precisa reserva",
      sellsOut: "Não, exceto a cerimônia formal",
      tip: "Pegue senha no Nakamura Tokichi assim que chegar e vá ao templo enquanto espera — a senha funciona por celular.",
    },
    bestTime: "Sair de Kyoto 9h, voltar ~15h.",
    december: "Baixa temporada: você consegue mesa nas casas de chá sem drama. O chá quente cai bem no frio. Byodo-in fecha 17h.",
    swapFor: "ESTE É O PEDIDO DO PEDRO QUE FICOU FORA. Troca pela tarde de compras de quarta 16/12 (Shijo-Kawaramachi), que é o bloco menos essencial dos três dias de Kyoto.",
    combines: [],
  },
  {
    id: "k-arashiyama", city: "kyoto", area: "Arashiyama", cat: "natureza",
    name: "Arashiyama: bambuzal + macacos", hours: 4, costBRL: 26, costYen: 800,
    match: "pedro", level: "alto", effort: "medio", rating: 4.4, solo: "pedro",
    lat: 35.0170, lng: 135.6710,
    what: "Túnel de bambus gigantes, ponte Togetsukyo e um morro com macacos selvagens e vista da cidade.",
    says: {
      good: ["O bambuzal às 7h, sem ninguém, é surreal", "O Iwatayama (macacos, ¥800) tem a melhor vista panorâmica de Kyoto"],
      bad: ["Depois das 9h o bambuzal vira fila de selfie — e ele é bem mais curto do que parece nas fotos (uns 400m)", "A subida do morro dos macacos dá 20min puxados"],
    },
    tickets: { where: "Bambuzal é grátis; Iwatayama ¥800 na entrada", when: "—", sellsOut: "Não", tip: "Natureza é prioridade 1 do Pedro e 8 da Gio — este é o candidato natural a programa individual dele, igual ao Fushimi." },
    bestTime: "Chegar 7h30 no bambuzal. Depois das 9h não vale.",
    december: "Baixa temporada, sem as multidões de novembro. Bambu fica verde o ano todo, então dezembro não tira nada. Frio de manhã é cortante ali no rio.",
    swapFor: "Meia manhã. Pode virar programa solo do Pedro enquanto a Gio faz compras no centro.",
    combines: [],
  },
  {
    id: "k-nishiki", city: "kyoto", area: "Centro", cat: "comida",
    name: "Mercado Nishiki", hours: 2, costBRL: 0, spendBRL: 90,
    match: "ambos", level: "alto", effort: "baixo", rating: 4.3,
    lat: 35.0050, lng: 135.7649,
    what: "400m de galeria coberta com 130 barracas — tamagoyaki, tofu de soja preta, espetinho de polvo com ovo de codorna dentro.",
    says: {
      good: ["'A cozinha de Kyoto' — comida de rua é prioridade nº1 de vocês", "Coberto: imune a chuva e frio"],
      bad: ["Proibido comer andando na maioria das barracas — tem que comer em pé ali mesmo", "Virou bem turístico nos últimos anos"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Vá com fome às 11h. Leve dinheiro." },
    bestTime: "11h–13h. Fecha ~18h, várias barracas fecham antes.",
    december: "Alta de caranguejo e ostra. Chá quente e amazake nas barracas.",
    swapFor: "Já está no roteiro-base (segunda 14/12, tarde de chegada).",
    inBase: true,
    combines: ["k-pontocho"],
  },
  {
    id: "k-pontocho", city: "kyoto", area: "Pontocho/Gion", cat: "noite",
    name: "Pontocho + Gion à noite", hours: 2.5, costBRL: 0, spendBRL: 180,
    match: "ambos", level: "alto", effort: "baixo", rating: 4.6,
    lat: 35.0044, lng: 135.7710,
    what: "Viela de lanternas entre o rio Kamo e Kawaramachi, com restaurantes de todos os preços. Gion, ao lado, é o distrito das casas de chá.",
    says: {
      good: ["No fim da tarde dá para ver maiko indo trabalhar — sem tour, só andando pela Hanamikoji", "A viela à noite com as lanternas acesas é a imagem que as pessoas guardam de Kyoto"],
      bad: ["Restaurantes com vista do rio cobram 20% a mais", "É PROIBIDO fotografar de perto nas ruelas privadas de Gion — multa de ¥10.000"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Restaurantes concorridos sim — reservar pelo hotel", tip: "Os restaurantes do lado oeste (sem vista do rio) são melhores e mais baratos." },
    bestTime: "17h30–18h para pegar as lanternas acendendo e a chance de ver maiko.",
    december: "Escurece 16h50 em Kyoto, então as lanternas acendem cedo — dá para jantar e ainda estar de volta ao hotel razoavelmente cedo.",
    swapFor: "Já está no roteiro-base (segunda 14/12).",
    inBase: true,
    combines: ["k-nishiki"],
  },
  {
    id: "k-philosopher", city: "kyoto", area: "Higashiyama Norte", cat: "natureza",
    name: "Caminho do Filósofo + Ginkaku-ji", hours: 2.5, costBRL: 16, costYen: 500,
    match: "pedro", level: "alto", effort: "medio", rating: 4.3,
    lat: 35.0270, lng: 135.7940,
    what: "Trilha de 2km à beira de um canal, ligando o Pavilhão de Prata (Ginkaku-ji) ao templo Nanzen-ji, com cafés no caminho.",
    says: {
      good: ["Caminhada tranquila, quase sem turista fora da temporada de cerejeira", "Ginkaku-ji tem o jardim de areia rastelada mais perfeito de Kyoto"],
      bad: ["Sem as cerejeiras (abril) ou as folhas (novembro), o canal é discreto", "2km a pé no frio"],
    },
    tickets: { where: "Caminho é livre; Ginkaku-ji ¥500 na bilheteria", when: "—", sellsOut: "Não", tip: "Faça no sentido Ginkaku-ji → Nanzen-ji: é levemente descendente." },
    bestTime: "Manhã. Ginkaku-ji fecha 17h no inverno.",
    december: "Em dezembro o canal fica nu — é o mês menos fotogênico do ano aqui. Vale pela caminhada e pelo Ginkaku-ji, não pela paisagem do canal.",
    swapFor: "Meia manhã. Concorre diretamente com Arashiyama — os dois são 'natureza para o Pedro'.",
    combines: [],
  },
  {
    id: "k-nijo", city: "kyoto", area: "Centro", cat: "templo",
    name: "Castelo Nijo", hours: 1.5, costBRL: 42, costYen: 1300,
    match: "ambos", level: "medio", effort: "baixo", rating: 4.4,
    lat: 35.0142, lng: 135.7481,
    what: "Castelo do shogun, patrimônio UNESCO, famoso pelo 'assoalho rouxinol' que canta ao pisar — sistema antigo contra ninja.",
    says: {
      good: ["É castelo, não templo: resolve o veto do Pedro a maratona de templo", "O assoalho que range de propósito é divertido"],
      bad: ["Não se pode fotografar dentro", "O jardim é melhor em outras estações"],
    },
    tickets: { where: "Bilheteria ¥1.300 (castelo + palácio Ninomaru)", when: "No dia", sellsOut: "Não", tip: "Se quiserem um 'terceiro templo' que não seja templo, é este." },
    bestTime: "Manhã. Fecha 17h (última entrada 16h).",
    december: "O evento de projeção NAKED de outono costuma terminar no começo de dezembro — nas datas de vocês (14–17/12) provavelmente já terá encerrado. Confirme antes de contar com visita noturna.",
    swapFor: "Pode substituir o Kinkaku-ji se quiserem variar o tipo de atração.",
    combines: [],
  },
  {
    id: "k-nara", city: "kyoto", area: "Nara", cat: "batevolta",
    name: "Nara — cervos + Todai-ji", hours: 6, costBRL: 26, costYen: 800, spendBRL: 100,
    match: "ambos", level: "baixo", effort: "alto", rating: 4.6, cutByBoth: true,
    lat: 34.6851, lng: 135.8048,
    what: "Cervos que fazem reverência para ganhar bolacha, e o Todai-ji, maior Buda de bronze do mundo dentro de um prédio de madeira gigante.",
    says: {
      good: ["O bate-volta mais recomendado do Kansai, quase unanimidade", "O Buda é maior do que qualquer foto sugere", "45min de Kyoto e 40min de Osaka"],
      bad: ["Os cervos roubam papel, mapa e comida da mão — e dão cabeçada", "Cortado pelos dois no questionário"],
    },
    tickets: { where: "Todai-ji: ¥800 na bilheteria. Bolacha de cervo: ¥200 nas barracas", when: "No dia", sellsOut: "Não", tip: "Guarde o mapa no bolso antes de comprar bolacha — os cervos comem papel." },
    bestTime: "Sair 9h, voltar ~16h.",
    december: "Baixa temporada. Os cervos ficam com pelagem de inverno e continuam ativos. Parque é aberto, então o frio pesa.",
    swapFor: "Come meio dia. Vocês dois cortaram — só entra se mudarem de ideia, tirando meio dia de outro bloco.",
    combines: [],
  },
  {
    id: "k-quimono", city: "kyoto", area: "Higashiyama", cat: "arte",
    name: "Aluguel de quimono", hours: 5, costBRL: 130, costYen: 4000,
    match: "ambos", level: "baixo", effort: "medio", rating: 4.2,
    lat: 35.0037, lng: 135.7780,
    what: "Aluguel de quimono/yukata por um dia, com vestimenta feita por profissional e opção de penteado.",
    says: {
      good: ["As fotos nas ladeiras de Higashiyama ficam lindas", "Inclui vestir e devolver no fim do dia"],
      bad: ["Anda-se devagar e com frio — quimono de inverno não é quente", "Ambos pontuaram experiência cultural baixo (Pedro 8, Gio 5)"],
    },
    tickets: { where: "Lojas em Gion/Kiyomizu (Yumeyakata, Okamoto)", when: "Reserva online com dias de antecedência", sellsOut: "Fins de semana sim", tip: "Peça o pacote com haori (casaco) — em dezembro sem ele você congela." },
    bestTime: "Retirar 9h, devolver 17h30.",
    december: "Frio de verdade. Quem faz em dezembro reclama do frio nos pés (as sandálias são abertas). Existe opção com meia térmica.",
    swapFor: "Baixa prioridade para os dois — listado por ser clássico de Kyoto, não por bater com o perfil de vocês.",
    combines: [],
  },

  // ==================== OSAKA ====================
  {
    id: "o-kaiyukan", city: "osaka", area: "Baía", cat: "arte",
    name: "Aquário Kaiyukan", hours: 3, costBRL: 88, costYen: 2700,
    match: "gio", level: "alto", effort: "medio", rating: 4.5,
    lat: 34.6547, lng: 135.4290,
    what: "Um dos maiores aquários do mundo. O tanque central tem 9m de profundidade e atravessa 8 andares, com tubarão-baleia dentro.",
    says: {
      good: ["O percurso desce em espiral em volta do tanque central — design muito elogiado", "Pedido explícito da Gio no questionário"],
      bad: ["Fica cheio no fim de semana", "O debate ético sobre tubarão-baleia em cativeiro incomoda parte dos visitantes"],
    },
    tickets: {
      where: "kaiyukan.com (oficial), Klook ou KKday",
      when: "Compre online — evita a fila da bilheteria, que é a maior demora",
      sellsOut: "Raramente esgota, mas a fila presencial passa de 40min no fim de semana",
      tip: "O combo com a roda-gigante Tempozan ao lado sai mais barato que separado.",
    },
    bestTime: "Já está no roteiro-base às 14h de quinta 17/12. Quinta é dia bom: menos gente.",
    december: "Indoor e aquecido. Perfeito para a tarde de chegada em Osaka, que é quando vocês estarão cansados da mudança de cidade.",
    swapFor: "Já está no roteiro-base.",
    inBase: true,
    combines: ["o-tempozan"],
  },
  {
    id: "o-dotonbori", city: "osaka", area: "Namba", cat: "comida",
    name: "Dotonbori + Kuromon Market", hours: 3.5, costBRL: 0, spendBRL: 200,
    match: "ambos", level: "alto", effort: "medio", rating: 4.6,
    lat: 34.6687, lng: 135.5013,
    what: "O canal do letreiro do Glico Man, com takoyaki e okonomiyaki em cada esquina. O Kuromon, a 10min, é o mercado coberto com 150 barracas de frutos do mar grelhados na hora.",
    says: {
      good: ["Prioridade nº1 combinada de vocês (comida de rua) e os dois marcaram noite de bar aqui", "Kuromon: wagyu em espeto e caranguejo grelhado na sua frente", "Funciona de dia (Kuromon) e de noite (Dotonbori)"],
      bad: ["Dotonbori é turístico e os preços refletem isso", "Kuromon fecha cedo (~17h)", "Takoyaki sai a ¥600 e queima a boca — deixe esfriar"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Vá ao Kuromon antes das 16h e emende no Dotonbori quando escurecer. Leve dinheiro." },
    bestTime: "Kuromon 15h–17h, Dotonbori a partir das 18h.",
    december: "Frutos do mar de inverno no auge no Kuromon (caranguejo, ostra, vieira). Dotonbori ganha iluminação de Natal no canal.",
    swapFor: "Já está no roteiro-base (quinta 17/12 e domingo 20/12).",
    inBase: true,
    combines: ["o-hozenji", "o-uranamba"],
  },
  {
    id: "o-himeji", city: "osaka", area: "Himeji", cat: "batevolta",
    name: "Castelo de Himeji", hours: 6, costBRL: 33, costYen: 1000,
    match: "gio", level: "alto", effort: "alto", rating: 4.8,
    lat: 34.8394, lng: 134.6939,
    what: "O único grande castelo japonês original — nunca foi destruído por guerra, incêndio ou terremoto. Patrimônio UNESCO, apelidado de Garça Branca.",
    says: {
      good: ["Consistentemente apontado como o castelo mais impressionante do Japão", "Pedido explícito da Gio", "30–50min de Osaka de shinkansen"],
      bad: ["A subida interna é de escada de madeira íngreme, quase vertical nos últimos andares — e de meia (tira sapato)", "No alto da temporada dão senha e você espera para subir", "O interior é vazio: é estrutura de madeira, não mobília"],
    },
    tickets: {
      where: "Bilheteria na entrada: ¥1.000 (castelo) ou ¥1.050 no combo com o jardim Koko-en",
      when: "No dia — não precisa antecipar",
      sellsOut: "Não, mas em pico dão senha de horário para subir a torre",
      tip: "Pegue o combo com o Koko-en: o jardim custa só ¥50 a mais no pacote.",
    },
    bestTime: "Já está no roteiro-base às 8h de sexta 18/12. Chegar cedo é exatamente certo — evita a senha de espera.",
    december: "Baixa temporada: sem fila de senha, provavelmente. O castelo branco contra céu limpo de inverno rende. Leve meia grossa: você sobe descalço de sapato, só de meia, em piso de madeira gelado.",
    swapFor: "Já está no roteiro-base, junto com Kobe.",
    inBase: true,
    combines: ["o-kobe"],
  },
  {
    id: "o-kobe", city: "osaka", area: "Kobe", cat: "batevolta",
    name: "Kobe — Kitano + carne de Kobe", hours: 5, costBRL: 0, spendBRL: 400,
    match: "pedro", level: "alto", effort: "alto", rating: 4.4,
    lat: 34.7019, lng: 135.1888,
    what: "Bairro das casas de comerciantes ocidentais do século XIX numa ladeira com vista do porto. E, claro, a carne.",
    says: {
      good: ["Pedido explícito do Pedro", "Steak de Kobe de verdade sai ¥6.000–15.000 no almoço (bem menos que no jantar)", "Kitano é fofo e diferente do resto do Japão"],
      bad: ["As casas cobram ¥500–750 cada uma — e por dentro são pouca coisa", "Carne de Kobe autêntica é cara; restaurante barato costuma ser outra carne"],
    },
    tickets: {
      where: "Bairro é livre. Restaurantes de carne: reservar pelo hotel ou Tabelog",
      when: "Reservar o restaurante com dias de antecedência",
      sellsOut: "Os bons sim, principalmente sexta à noite",
      tip: "Peça o MENU DE ALMOÇO mesmo que vão jantar: a mesma carne sai por metade do preço no almoço em muitas casas.",
    },
    bestTime: "Já está no roteiro-base às 14h de sexta 18/12, emendando com Himeji.",
    december: "O Kobe Luminarie, festival de luzes em memória do terremoto de 1995, acontece tipicamente em dezembro — confirme as datas de 2026, porque se cair nas suas, é uma das iluminações mais impressionantes do país e resolve o desejo de iluminação do Pedro.",
    swapFor: "Já está no roteiro-base.",
    inBase: true,
    combines: ["o-himeji"],
  },
  {
    id: "o-arima", city: "osaka", area: "Arima", cat: "batevolta",
    name: "Arima Onsen — banho privativo (kashikiri)", hours: 8, costBRL: 114, costYen: 3500,
    match: "pedro", level: "alto", effort: "alto", rating: 4.5,
    lat: 34.7981, lng: 135.2478,
    what: "Um dos onsens mais antigos do Japão, na montanha atrás de Kobe. O banho PRIVATIVO reservado resolve a tatuagem e o fato de serem irmãos de uma vez só.",
    says: {
      good: ["Kinsen (água dourada, ferruginosa) e Ginsen (prateada) — duas águas diferentes na mesma vila", "A vila é pequena e dá para andar tudo a pé", "Privativo: sem constrangimento e sem regra de tatuagem"],
      bad: ["O kashikiri é por hora e precisa reserva — não dá para chegar e usar", "A vila enche de excursão japonesa no fim de semana, e vocês vão num sábado"],
    },
    tickets: {
      where: "Direto com a casa de banho ou ryokan. Taiko-no-Yu e Arima Onsen Tenzan oferecem kashikiri",
      when: "RESERVAR COM ANTECEDÊNCIA — está na sua lista de pendências",
      sellsOut: "Sim, e vocês vão num sábado, o pior dia",
      tip: "Peça ao hotel de Osaka para ligar e reservar em japonês — a maioria das casas não tem reserva online em inglês.",
    },
    bestTime: "Já está no roteiro-base às 9h de sábado 19/12, voltando 17h.",
    december: "É O mês para onsen: entrar na água quente com ar gelado é a experiência inteira. Arima é mais alta e mais fria que Osaka — leve casaco pesado para a caminhada na vila.",
    swapFor: "Já está no roteiro-base.",
    inBase: true,
    combines: [],
  },
  {
    id: "o-osaka-castle", city: "osaka", area: "Chuo", cat: "templo",
    name: "Castelo de Osaka + parque", hours: 2.5, costBRL: 20, costYen: 600,
    match: "ambos", level: "medio", effort: "medio", rating: 4.2,
    lat: 34.6873, lng: 135.5259,
    what: "Castelo reconstruído em concreto (1931) com museu dentro e elevador. O parque em volta é enorme e gratuito.",
    says: {
      good: ["O parque e a vista externa são ótimos e de graça", "O museu conta bem a história de Hideyoshi"],
      bad: ["Por dentro é museu moderno com elevador, não castelo histórico — quem vem de Himeji acha decepcionante", "Fila para o elevador no alto da temporada"],
    },
    tickets: { where: "Bilheteria ¥600", when: "No dia", sellsOut: "Não", tip: "Se já forem a Himeji, considere só o parque externo aqui (grátis) e use o tempo em outra coisa." },
    bestTime: "Já está no roteiro-base às 9h de domingo 20/12.",
    december: "Parque aberto e frio. As ameixeiras do jardim só florescem em fevereiro. Castelo fecha 17h.",
    swapFor: "Já está no roteiro-base. É o bloco mais 'substituível' do dia 20.",
    inBase: true,
    combines: [],
  },
  {
    id: "o-umeda-sky", city: "osaka", area: "Umeda", cat: "vista",
    name: "Umeda Sky Building", hours: 1.5, costBRL: 49, costYen: 1500,
    match: "ambos", level: "alto", effort: "baixo", rating: 4.5,
    lat: 34.7053, lng: 135.4906,
    what: "Observatório circular a céu aberto ligando duas torres por uma ponte suspensa a 170m. A escada rolante que atravessa o vazio entre as torres é parte do passeio.",
    says: {
      good: ["Melhor mirante de Osaka, com boa margem", "O anel externo é aberto, sem vidro", "A escada rolante suspensa impressiona mais que a vista"],
      bad: ["Venta muito lá em cima", "Fica um pouco afastado da estação de Umeda — 10min a pé por um caminho confuso"],
    },
    tickets: { where: "Bilheteria ou site oficial (kuchu-teien.com)", when: "No dia", sellsOut: "Não", tip: "Suba ~40min antes do pôr do sol: você pega dia, pôr do sol e noite na mesma entrada." },
    bestTime: "Já está no roteiro-base às 15h30 de domingo 20/12 — e o pôr do sol em Osaka nessa data é ~16h50, então o horário está perfeito.",
    december: "Ar limpo de inverno = melhor visibilidade do ano. O piso do observatório tem iluminação que acende à noite.",
    swapFor: "Já está no roteiro-base.",
    inBase: true,
    combines: ["o-hep-five"],
  },
  {
    id: "o-hozenji", city: "osaka", area: "Namba", cat: "templo",
    name: "Hozenji Yokocho", hours: 0.5, costBRL: 0,
    match: "ambos", level: "alto", effort: "baixo", rating: 4.4,
    lat: 34.6685, lng: 135.5030,
    what: "Viela de pedra a dois passos do caos de Dotonbori, com um templinho cuja estátua está coberta de musgo de tanta água jogada pelos fiéis.",
    says: {
      good: ["30 minutos e você tem 'o templo' sem gastar meio dia — resolve o veto do Pedro", "O contraste com o neon de Dotonbori ao lado é absurdo", "Joga água na estátua e faz o pedido"],
      bad: ["É pequeno mesmo — não espere mais que uma viela"],
    },
    tickets: { where: "Livre, aberto 24h", when: "—", sellsOut: "Não", tip: "Encaixa dentro da noite de Dotonbori que já está marcada, sem custo de tempo." },
    bestTime: "À noite, com as lanternas acesas, indo ou voltando do jantar.",
    december: "Sem sazonalidade. Como está no meio do caminho da noite de bar, é o extra de menor custo do roteiro inteiro.",
    swapFor: "Custo zero de roteiro — acontece no caminho.",
    combines: ["o-dotonbori"],
  },
  {
    id: "o-uranamba", city: "osaka", area: "Namba", cat: "noite",
    name: "Ura-Namba (a Osaka de verdade)", hours: 2.5, costBRL: 0, spendBRL: 160,
    match: "ambos", level: "alto", effort: "baixo", rating: 4.5,
    lat: 34.6640, lng: 135.5035,
    what: "As vielas atrás do neon de Dotonbori, onde o pessoal de Osaka realmente come e bebe.",
    says: {
      good: ["Metade do preço de Dotonbori e o dobro da qualidade", "Izakayas pequenos onde o dono conversa", "Os dois marcaram 'noite de bar em Dotonbori' — esta é a versão boa disso"],
      bad: ["Quase nada em inglês", "Lugares minúsculos, às vezes tem que esperar"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Procure o prédio Misono, dos anos 50, com bares em vários andares." },
    bestTime: "A partir das 19h.",
    december: "Interno e aquecido. Ótimo plano para a noite livre de sábado 19/12, depois de voltar do Arima.",
    swapFor: "Encaixa na noite livre do dia do Arima sem tirar nada.",
    combines: ["o-dotonbori", "o-hozenji"],
  },
  {
    id: "o-museu-habitacao", city: "osaka", area: "Tenjinbashi", cat: "arte",
    name: "Museu da Habitação e Vida de Osaka", hours: 2, costBRL: 20, costYen: 600,
    match: "gio", level: "medio", effort: "baixo", rating: 4.3, priority: true, solo: "gio",
    lat: 34.7033, lng: 135.5188,
    what: "Uma rua inteira de Osaka do período Edo reconstruída em tamanho real dentro de um prédio, com ciclo de iluminação simulando o dia inteiro.",
    says: {
      good: ["Você anda dentro da cidade antiga, não olha de longe", "Dá para alugar quimono e circular pela réplica (~¥2.000)", "A iluminação muda do amanhecer ao anoitecer a cada 20 minutos"],
      bad: ["Pequeno: 1h30 a 2h resolve", "Legendas em inglês são resumidas"],
    },
    tickets: { where: "konjyakukan.com ou bilheteria, ¥600", when: "No dia", sellsOut: "Não", tip: "Fica em cima da estação Tenjinbashisuji 6-chome, que é a maior galeria comercial do Japão — dá para emendar." },
    bestTime: "Manhã ou início da tarde. Fecha 17h (última entrada 16h30) e fecha às terças.",
    december: "Indoor e aquecido. ESTE É O MUSEU QUE FALTAVA: museus é a categoria em que vocês mais divergem (Gio 4, Pedro 7), e nenhum entrou no roteiro. Serve como programa individual da Gio, no mesmo espírito do split do Fushimi.",
    swapFor: "Programa individual da Gio na manhã livre de segunda 21/12, ou em paralelo a algo do Pedro.",
    combines: [],
  },
  {
    id: "o-shinsekai", city: "osaka", area: "Shinsekai", cat: "comida",
    name: "Shinsekai + Torre Tsutenkaku", hours: 2.5, costBRL: 33, costYen: 1000, spendBRL: 120,
    match: "ambos", level: "alto", effort: "medio", rating: 4.3,
    lat: 34.6524, lng: 135.5063,
    what: "Bairro retrô dos anos 1910 com neon antigo, a torre Tsutenkaku e a rua do kushikatsu (espetinho empanado).",
    says: {
      good: ["O bairro mais 'Osaka' que existe — brega, barulhento e divertido", "Kushikatsu é barato e viciante", "Muito menos turista que Dotonbori"],
      bad: ["Regra sagrada: NÃO se molha o espetinho duas vezes no molho comunitário", "À noite a área fica mais pesada que o resto da cidade"],
    },
    tickets: { where: "Torre Tsutenkaku ¥1.000 na bilheteria", when: "No dia", sellsOut: "Não", tip: "O Billiken, deus da sorte no topo da torre: esfregue o pé dele." },
    bestTime: "Fim de tarde, com o neon acendendo.",
    december: "Neon antigo + ar frio = a melhor versão do bairro. Kushikatsu quente cai bem.",
    swapFor: "Alternativa a uma das noites de Dotonbori, para não repetir o mesmo bairro duas vezes.",
    combines: [],
  },
  {
    id: "o-hep-five", city: "osaka", area: "Umeda", cat: "vista",
    name: "Roda-gigante HEP FIVE", hours: 0.75, costBRL: 23, costYen: 700,
    match: "ambos", level: "medio", effort: "baixo", rating: 4.0,
    lat: 34.7038, lng: 135.4988,
    what: "Roda-gigante vermelha de 106m montada NO TELHADO de um shopping, no meio de Umeda.",
    says: {
      good: ["Barata e rápida", "A cabine tem som Bluetooth: você põe sua música"],
      bad: ["Vista bem inferior à do Umeda Sky, que fica a 10min", "15 minutos de volta e acabou"],
    },
    tickets: { where: "Bilheteria no 7º andar do shopping", when: "No dia", sellsOut: "Não", tip: "Se já forem ao Umeda Sky no mesmo dia, esta vira redundante." },
    bestTime: "Depois de escurecer, ~17h.",
    december: "Cabine fechada e aquecida — opção de vista para dia de chuva ou vento, quando o Umeda Sky fica desconfortável.",
    swapFor: "Alternativa barata ao Umeda Sky, não complemento.",
    combines: ["o-umeda-sky"],
  },
  {
    id: "o-usj", city: "osaka", area: "Konohana", cat: "parque",
    name: "Universal Studios Japan (Super Nintendo World)", hours: 11, costBRL: 280, costYen: 8600,
    match: "pedro", level: "baixo", effort: "alto", rating: 4.6, cutByBoth: true,
    lat: 34.6654, lng: 135.4323,
    what: "A maior atração de Osaka. O Super Nintendo World põe você dentro do mundo do Mario, com pulseira que marca pontos de verdade.",
    says: {
      good: ["Super Nintendo World é considerado o melhor mundo temático já construído", "A área do Harry Potter também é forte"],
      bad: ["Cortado pelos dois no questionário", "Entrada na área do Nintendo exige senha por horário, mesmo tendo ingresso", "Filas de 2h+ sem Express Pass (que custa ¥7.000–10.000 à parte)"],
    },
    tickets: {
      where: "usj.co.jp (oficial), Klook ou KKday",
      when: "Comprar com meses de antecedência — e a área do Nintendo separada",
      sellsOut: "Sim, tanto o ingresso quanto a senha do Nintendo World",
      tip: "Se entrar, compre o Express Pass junto: sem ele a experiência muda completamente.",
    },
    bestTime: "Chegar 8h, sair depois de escurecer.",
    december: "Roda evento de Natal. Mas é um dia inteiro e vocês dois cortaram no questionário.",
    swapFor: "ALTO CUSTO: substituiria o dia de Himeji+Kobe (pedidos dos dois) ou o dia de Arima. Não recomendo tirar nenhum deles.",
    combines: [],
  },
  {
    id: "o-shinsaibashi", city: "osaka", area: "Shinsaibashi", cat: "compras",
    name: "Shinsaibashi + Amerikamura", hours: 2.5, costBRL: 0, spendBRL: 300,
    match: "ambos", level: "alto", effort: "medio", rating: 4.3,
    lat: 34.6723, lng: 135.5010,
    what: "600m de galeria coberta com 180 lojas, e ao lado a Amerikamura, o bairro de streetwear e brechó de Osaka.",
    says: {
      good: ["Compras é prioridade nº2 combinada de vocês", "Coberto: chuva e frio não atrapalham", "Amerikamura tem vintage mais barato que Tóquio"],
      bad: ["Muito cheio à noite", "Lojas de rede se repetem"],
    },
    tickets: { where: "Não precisa", when: "—", sellsOut: "Não", tip: "Tax-free acima de ¥5.000 por loja, com passaporte em mãos." },
    bestTime: "Já está no roteiro-base às 18h de domingo 20/12.",
    december: "Promoções de Natal rolando. Fukubukuro (sacola-surpresa) só a partir do fim do mês — vocês saem antes.",
    swapFor: "Já está no roteiro-base.",
    inBase: true,
    combines: [],
  },
  {
    id: "o-shitennoji", city: "osaka", area: "Tennoji", cat: "templo",
    name: "Shitenno-ji", hours: 1, costBRL: 10, costYen: 300,
    match: "ambos", level: "medio", effort: "baixo", rating: 4.2,
    lat: 34.6532, lng: 135.5162,
    what: "O templo budista oficial mais antigo do Japão (593 d.C.), com pagode de cinco andares.",
    says: {
      good: ["Histórico de verdade — anterior a qualquer coisa em Kyoto", "Terrenos externos são gratuitos"],
      bad: ["Reconstruído em concreto depois da guerra", "Quem vem de Kyoto acha sem graça"],
    },
    tickets: { where: "Bilheteria ¥300 (área interna); externo é grátis", when: "No dia", sellsOut: "Não", tip: "No dia 21 de cada mês tem feira de antiguidades no terreno — e vocês estarão em Osaka no dia 21 de manhã." },
    bestTime: "Manhã. Fecha 16h30 no inverno.",
    december: "A feira do dia 21 cai exatamente na manhã livre de vocês antes de seguir para Narita — pode ser um bom último programa em Osaka.",
    swapFor: "Encaixa na manhã livre de segunda 21/12.",
    combines: [],
  },
  {
    id: "o-nakanoshima-illum", city: "osaka", area: "Nakanoshima", cat: "natal",
    name: "Iluminações de Nakanoshima (Osaka Hikari no Renaissance)", hours: 1.5, costBRL: 0,
    match: "pedro", level: "medio", effort: "baixo", rating: 4.3,
    lat: 34.6937, lng: 135.4990,
    what: "O festival de luzes de Osaka na ilha fluvial, com projeção mapeada na fachada da Biblioteca Central e um túnel de luz ao longo do rio.",
    says: {
      good: ["A projeção na biblioteca neoclássica é o ponto alto", "Gratuito na maior parte"],
      bad: ["Gio marcou iluminações como o item que corta mais fácil", "Cheio nos fins de semana de dezembro"],
    },
    tickets: { where: "Gratuito; algumas atrações do festival cobram à parte", when: "—", sellsOut: "Não", tip: "Confirme as datas de 2026 perto da viagem — o festival costuma rodar na segunda quinzena de dezembro." },
    bestTime: "A partir das 17h, quando já escureceu.",
    december: "Roda tipicamente em dezembro e vocês estarão lá na segunda quinzena. É a chance de Osaka para o desejo de iluminação do Pedro.",
    swapFor: "Encaixa numa das noites, no caminho entre Umeda e o hotel.",
    combines: ["o-umeda-sky"],
  },
];

// Bate-voltas com informação consolidada de deslocamento
export const DAY_TRIPS = [
  {
    id: "dt-himeji", name: "Himeji", from: "Osaka", time: "30–50 min", cost: "¥1.520–2.310",
    mode: "Shinkansen", hours: 6, actId: "o-himeji",
    why: "O único castelo original e intacto do Japão. Pedido da Gio.",
    inBase: true,
  },
  {
    id: "dt-kobe", name: "Kobe", from: "Osaka", time: "~22 min", cost: "¥420–1.110",
    mode: "JR Special Rapid", hours: 5, actId: "o-kobe",
    why: "Bairro Kitano + a carne. Pedido do Pedro. Emenda com Himeji no mesmo dia.",
    inBase: true,
  },
  {
    id: "dt-arima", name: "Arima Onsen", from: "Osaka", time: "50–70 min", cost: "~¥1.100–1.400",
    mode: "Ônibus direto", hours: 8, actId: "o-arima",
    why: "Banho privativo — resolve tatuagem e o fato de serem irmãos.",
    inBase: true,
  },
  {
    id: "dt-uji", name: "Uji", from: "Kyoto", time: "~30 min", cost: "¥240",
    mode: "JR Nara Line", hours: 5, actId: "k-uji",
    why: "Capital do matcha + Byodo-in. O pedido do Pedro que ficou fora do roteiro.",
    priority: true,
  },
  {
    id: "dt-nara", name: "Nara", from: "Kyoto (45min) ou Osaka (40min)", time: "40–50 min", cost: "¥720",
    mode: "JR ou Kintetsu", hours: 6, actId: "k-nara",
    why: "Cervos + maior Buda de bronze do mundo. Cortado pelos dois, mas é o bate-volta mais recomendado do Kansai.",
    cutByBoth: true,
  },
  {
    id: "dt-arashiyama", name: "Arashiyama", from: "Kyoto", time: "~20 min", cost: "¥240",
    mode: "JR Sagano", hours: 4, actId: "k-arashiyama",
    why: "Bambuzal + macacos. Dentro da própria Kyoto — o mais barato e rápido da lista.",
  },
  {
    id: "dt-hiroshima", name: "Hiroshima + Miyajima", from: "Osaka", time: "~90 min", cost: "~¥10.000",
    mode: "Shinkansen + ferry", hours: 12,
    why: "Memorial da Paz e o torii flutuante. É o bate-volta mais impactante do Japão, mas consome o dia inteiro e não foi marcado por nenhum dos dois.",
    heavy: true,
  },
  {
    id: "dt-koyasan", name: "Koyasan", from: "Osaka", time: "~2h", cost: "¥1.700",
    mode: "Nankai + funicular", hours: 24,
    why: "Mosteiro na montanha com pernoite em templo. Exige abrir mão de uma noite de Osaka ou Kyoto.",
    heavy: true,
  },
];
